# This is a sample build configuration for Javascript (Node.js).
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:7.10.0

# - test
# - build
stages:
  - deploy

# TODO: Add unit tests
# Run test scripts:
# stage: test
# script:
#   - npm install
#   - npm test

Publish to netlify:
  stage: deploy
  script:
    # Triggers a build trigger from netlify
    - curl -X POST -d '{}' https://api.netlify.com/build_hooks/59e2a0f6a6188f0371e1ce3e

